### ISSUE TITLE
Response headers

### ISSUE THREAD

**Issue by johnjohndoe** [skydoves/retrofit-adapters#28]
**Is your feature request related to a problem?**

Are you planning to expose the header fields of an HTTP response?

**Describe the solution you'd like:**

Not sure if this is possible with the `Result` type.

**Describe alternatives you've considered:**

One can use `Call` or `retrofit2.Response` as an alternative.

**Comment by skydoves** [comment]
Hi @johnjohndoe, apologies for the delayed response. I believe this isn't achievable with the current library due to some limitations with the `Result` interface. Instead, I recommend trying [Sandwich](https://github.com/skydoves/sandwich), which offers greater flexibility and more extensive extensions.
